apiVersion: v1
kind: Service

metadata:
  name: zipkin
  namespace: ad-bidding-system

spec:
  selector:
    app: zipkin

  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30093

  type: NodePort