apiVersion: v1
kind: ConfigMap

metadata:
  name: campaign-service-config
  namespace: ad-bidding-system

data:
  SPRING_PROFILES_ACTIVE: docker

  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bidding_campaigndb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092